package com.trainconcierge.recommendation;

import com.trainconcierge.common.BaseEntity;
import com.trainconcierge.disruption.DisruptionEvent;
import com.trainconcierge.schedule.TrainSchedule;
import com.trainconcierge.user.User;
import jakarta.persistence.*;
import lombok.*;

import java.math.BigDecimal;
import java.time.Instant;

/**
 * An alternative journey suggestion generated by the recommendation engine
 * in response to a DisruptionEvent for a specific User.
 *
 * The engine may produce multiple recommendations per (disruption, user) pair,
 * ranked by score. The passenger accepts one → triggers a RebookingHistory entry.
 *
 * Relationships:
 * - Many Recommendations → One DisruptionEvent
 * - Many Recommendations → One User
 * - Many Recommendations → One TrainSchedule (the suggested alternative)
 * - One Recommendation → One RebookingHistory (if accepted)
 */
@Entity
@Table(name = "recommendations")
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class Recommendation extends BaseEntity {

    @ManyToOne(fetch = FetchType.LAZY, optional = false)
    @JoinColumn(name = "disruption_event_id", nullable = false)
    private DisruptionEvent disruptionEvent;

    @ManyToOne(fetch = FetchType.LAZY, optional = false)
    @JoinColumn(name = "user_id", nullable = false)
    private User user;

    /** The alternative train schedule being suggested. */
    @ManyToOne(fetch = FetchType.LAZY, optional = false)
    @JoinColumn(name = "suggested_schedule_id", nullable = false)
    private TrainSchedule suggestedSchedule;

    /**
     * AI/rule-based score (0.0 – 1.0).
     * Higher = better fit for the passenger's preferences.
     */
    @Column(nullable = false, precision = 4, scale = 3)
    private BigDecimal score;

    /** Estimated fare for the suggested alternative. */
    @Column(precision = 10, scale = 2)
    private BigDecimal estimatedFare;

    /** Human-readable reason e.g. "Next available direct service, 45 min later". */
    @Column(nullable = false, length = 500)
    private String reason;

    /** PENDING / ACCEPTED / DECLINED / EXPIRED */
    @Column(nullable = false, length = 20)
    @Builder.Default
    private String status = "PENDING";

    private Instant respondedAt;
}
